### PR TITLE
Better docstrings

### PR DESCRIPTION
**Pull request by Peder2911**
Wrote better docstrings for most important public functions and the
StepshiftedModels class.

### CODE REVIEW

**Comment by Peder2911** [comment]
What do you think about this documentation @hhegre ? Anything missing or unclear?

To see the added documentation, see this changelog:
https://github.com/prio-data/stepshift/pull/8/commits/637b2fdecce7d3cfd447801957e2edd68e736ffb

**Comment by jimdale** [comment]
New docstrings very clear and informative - looks great!

**Review by jimdale — APPROVED** [review]
much improved docstrings !

**Review by hhegre — APPROVED** [review]
This looks good. I am not sure I understand the table below, maybe that should be left out and we rather refer to the document that Tim is working on, plus the article?
     t │ 1   2   3   4   5   6   7  
      ────────────────────────────── 
      x │ 1   1   1   1
        │
      x1│     1   1   1   1
        │
      x2│         1   1   1   1
        │
      x3│             1   1   1   1
        │
      Ŷ1│     1   1   1   1
        │
      Ŷ2│         2   2   2   2
        │
      Ŷ3│             3   3   3   3
        │
      Ŷ │                 1   2   3

**Comment by Peder2911** [comment]
Agreed! Took it out.

Thanks both, merging.

**Pull request merged**
