### PR TITLE
feature/views api

### PR DESCRIPTION
**Pull request by Peder2911**
- Started writing ViEWS API for training and applying stepshifted models
- Working views API
- Updated clean make
- Noncontiguous units support

### CODE REVIEW

**Comment by Peder2911** [comment]
@hhegre me and Jim looked at this today, and I think we need your eyes on this to make sure it's working as intended.

**Comment by Peder2911** [comment]
Input from @mihaicroicu would also be appreciated.

**Comment by mihaicroicu** [comment]
Will look as soon as am done with other stuff.

**Comment by hhegre** [comment]
I have terribly much on my plate up to next Wednesday; will take a look Wednesday afternoon or Thursday. Would be useful if @Peder2911 or @jimdale took me through it, though (will be in Uppsala next week).

**Comment by Peder2911** [comment]
https://github.com/prio-data/stepshift/commit/342814d5bc05b2635d89444bd68c5774423a4338 is a basic confirmation that stepshifting is working as intended (or rather, in the way I understand it?)

**Comment by Peder2911** [comment]
I just added code to generate a step-combined column in https://github.com/prio-data/stepshift/commit/fe20882e6f4426c3373eacb4421d600cde337f3b.
The sc column is added by default when calling `mdl.predict(data)`.

**Review by Doktorandahl — APPROVED** [review]
Based on the predict_markov notebook the stepshifting seems to work just as intended!

**Comment by Peder2911** [comment]
For reference, predict_markov notebook demonstration is here: https://github.com/prio-data/views3_demo_notebook/blob/master/predict_markov/predict_markov.ipynb

**Comment by mihaicroicu** [comment]
Looks good to me, I would leave it as open as possible, since the whole thing seems to produce quite sane defaults.

**Review by mihaicroicu — APPROVED** [review]
Tested and works

**Comment by hhegre** [comment]
I have also looked at this now - it seems to be working as it should, with the exception that the end result, the target for the stepshifting, should be a 'square' box of predictions. I will try to specify. Not sure how to approve this formally in git..

**Review by hhegre — APPROVED** [review]
The step shifting part of this works as intended. The target result should have a different shape, but that seems to be a different question.

**Review by jimdale — APPROVED** [review]
Looks good to me!

**Pull request merged**
